const number = 45
try{
    throw new Error("Yeaah ..sorry")
        

    
    
}catch(e){
    console.log(e)
}